### ISSUE TITLE
Activer github pages

### ISSUE THREAD

**Issue by ghoullier** [cedric-legallo/tenon-io-slides#1]
Est ce que tu pourrais activer l'hebergement via github pages pour ton repo? Ca permettrait de voir directement les slides dans son navigateur à l'adresse: [http://cedric-legallo.github.io/tenon-io-slides/](http://cedric-legallo.github.io/tenon-io-slides/)

Les infos pour le mettre en place sont dispo ici: [https://pages.github.com/](https://pages.github.com/)

**Comment by cedric-legallo** [comment]
done
